--exclude ^include/asn1c/INTEGER\.h$
--exclude ^include/asn1c/asn_internal\.h$
--exclude ^src/BOOLEAN\.c$
--exclude ^src/INTEGER\.c$
--exclude ^src/NULL\.c$
--exclude ^src/NativeEnumerated\.c$
--exclude ^src/OCTET_STRING\.c$
--exclude ^src/REAL\.c$
--exclude ^src/UTCTime\.c$
--exclude ^src/asn1helpers\.c$
--exclude ^src/constr_CHOICE\.c$
--exclude ^src/constr_SEQUENCE_OF\.c$
--exclude ^src/constr_SET_OF\.c$
--exclude ^src/per_opentype\.c$
--exclude ^src/per_support\.c$
